### ISSUE TITLE
NumUsed is not defined

### ISSUE THREAD

**Issue by aviankona** [zhuker/lamejs#1]
Hi, 

I saw your project and was very impressed. 

While testing to see it's performance, I've came across an error.

"NumUsed is not defined" on lame.all.js line 15163.

Would appreciate a bug fix in order to complete the cycle.

Thanks,
Avi.

**Comment by zhuker** [comment]
fixed
let me know if it works for you.

**Comment by aviankona** [comment]
thanks for the fix,

now it throws "fill_buffer_resample is not defined"

lame.all.js:15169 Uncaught ReferenceError: fill_buffer_resample is not defined

**Comment by zhuker** [comment]
can you send me the code which reproduces the bug?
do you intentionally resample?

**Comment by aviankona** [comment]
Hi Alex, 

Here is my complete flow:
1. record audio with the WebAudio Api,
    block size 2048
    sample rate - according to the mic input (will probably be 44,100 or 48,000)

2. Convert it to WAV - preserving it's sample rate, using it's block size. defining the WAV output to mono. the function returns an UInt16Array.

3. Execute a copy of your function (from the example page) with the original sample rate and block size.

I'm executing the conversion in a web worker.

See conversion function below:
    function _newEncodeMp3( uint16Array ){
        var liblame = new lamejs();
        var mp3enc = new liblame.Mp3Encoder(1, ORIGINAL_SAMPLE_RATE, 16);
        var remaining = uint16Array.length;
        var maxSamples = ORIGINAL_BLOCK_SIZE;
        for (var i = 0; remaining >= maxSamples; i += maxSamples) {
            var mono = uint16Array.subarray(i, i + maxSamples);
            var mp3buf = mp3enc.encodeBuffer(mono);
            if (mp3buf.length > 0) {
                //TODO write to output
            }
            remaining -= maxSamples;
        }
        var mp3buf = mp3enc.flush();

        return mp3buf;
    }


Thanks for the support,
Avi.

**Comment by zhuker** [comment]
what was the ORIGINAL_SAMPLE_RATE when the code failed?

**Comment by zhuker** [comment]
are you sure you want 16kbps mp3? 
for such low bitrates lame does resampling to a lower sample rate

**Comment by aviankona** [comment]
My sample rate is 44100
what's the minimum kbps that you suggest?

**Comment by zhuker** [comment]
depends on your application
try 64 and let me know if it works for you

**Comment by zhuker** [comment]
just fixed the resampling code
should work with 16kbps now
try it

**Comment by aviankona** [comment]
Just tested it.

it fails on the initialization with the following error:
lame.all.js:15509 Uncaught ReferenceError: fs is not defined

**Comment by zhuker** [comment]
my bad, forgot to disable tests, just fixed

**Comment by aviankona** [comment]
Hi Alex,

Conversion function has finished successfully!

I'll create an output file and check the conversion.

Thanks!
Avi.
