### ISSUE TITLE
No return if buffer is too big

### ISSUE THREAD

**Issue by rehoehle** [zhuker/lamejs#12]
Hello,

i have a small problem converting the wav data to MP3 and i hope someone can help me. If my recording is too long and i use only 

```
var mp3buf = mp3encoder.encodeBuffer(buffer);
```

i get no result and some strange problems. So i tried to change my code to the chunked version. 

```
var mp3Data = [];
// Get Buffer and create new mp3encoder
var buffer = new Int16Array(this.result);

var mp3encoder = new lame.Mp3Encoder(1, recordRTC.sampleRate, 128);

// Encode main data
var sampleBlockSize = 1152;
 for (var x = 0; x < buffer.length; x += sampleBlockSize) {
    var sampleChunk = buffer.subarray(x, x + sampleBlockSize);
    var mp3buf = mp3encoder.encodeBuffer(sampleChunk);
    if (mp3buf.length > 0) {
        mp3Data.push(mp3buf);
    }
}
```

I don't get valid mp3 data then when i look at the output if mp3Data i get an array that contains many of Int8Array for every encoded chunk i think that is not correct. 

![screenshot at sep 23 22-10-23](https://cloud.githubusercontent.com/assets/223007/10057308/eb74268c-623f-11e5-99ea-b8fa7521c492.png)

When i use only the one line i get Output like this

```
[Int8Array[33333]]
    0: Int8Array[13123]
    1: Int8Array[123]
```

That looks like the left and right channel if u use then mp3Data[0] its working well and i have the mp3 data. But like i said its not working if the recording is too long. What is wrong?

**Comment by rehoehle** [comment]
Ok i have found a solution i don't know if its the current way but its working. Perhaps the i can change the documentation if its missing there. 

My solution is to forEach over the result and add the values:

	// Encode main data
	var sampleBlockSize = 1152;
	for (var x = 0; x < samples.length; x += sampleBlockSize) {
		var sampleChunk = samples.subarray(x, x + sampleBlockSize);
		var mp3buf = mp3encoder.encodeBuffer(sampleChunk);
		if (mp3buf.length > 0) {
			mp3buf.forEach(function(val) {
			mp3Data.push(val);
		});
        }
  
	// Flush and set last data to mp3Data
	mp3Data.push(mp3encoder.flush());
	mp3Data = new Int8Array(mp3Data);

After that convert it back to an Int8Array. Its possible that this errors came because i use RecordRTC.

**Comment by shanewho** [comment]
If you are pushing the result of encode into an array, you are right you will get an array of arrays. The reason I do that in my code is that I then create a blob `new Blob(blocks, {type: 'audio/mpeg'});` which can process multiple arrays of data. If you aren't using a Blob, you'll want a different way of storing/processing the data. Your foreach is one option, a `concat` might be simpler. It all depends on what you are going to do with the output.

**Comment by rehoehle** [comment]
I've tried now a lot of things and its not usable. After 20 seconds you get unusable data which are a lot longer then the original data. So its not working. I have now another solution without lamejs and zip the data and convert them on my server. I can't find another solution. Its really sad then i think the idea of lamejs is very good.
