### ISSUE TITLE
Using a web worker

### ISSUE THREAD

**Issue by javismiles** [zhuker/lamejs#15]
I'm obtaining better quality with this library than with 
https://github.com/blixt/js-lameworker

but blixt uses a web worker to run the conversion in the background improving in theory the performance,
would this be possible with this library as well?

best

**Comment by shanewho** [comment]
I'm using lamejs in a web worker and it works just fine. There isn't anything lame specific you need to do, just normal web worker stuff.

**Comment by javismiles** [comment]
that's great to know and thank you for replying so fast Shanewho :) do you also have any insights about this other issue i posted? https://github.com/zhuker/lamejs/issues/14
thank you so much
Jav

**Comment by logbon72** [comment]
I submitted a new PR for Web Worker example, it encodes both Mono & Stereo. 
https://github.com/zhuker/lamejs/pull/17

I also used this plugin in an AngularJS directive with RecorderJS, you can check it out here:  https://github.com/logbon72/angular-recorder

**Comment by zhuker** [comment]
i am closing this issues 
merged the PR a while ago
