### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by jamescostian** [zhuker/lamejs#19]
The README of this project mentions that the code works on "both on node and chrome", so why not put it on [npm](https://npmjs.com/)? All it takes is a `package.json` file, which npm can help you make if you just run `npm init` in the root of this project, and then you can `npm publish` it.

**Comment by zhuker** [comment]
https://www.npmjs.com/package/lamejs
let me know if it works for you

**Comment by jamescostian** [comment]
It works! Thank you!
