### ISSUE TITLE
Output is Silence - Format issue?

### ISSUE THREAD

**Issue by sb2702** [zhuker/lamejs#2]
In using the emscripten libmp3lame, I've been feeding it Float32Array buffer output straight from the user's microphone output

               this.node.onaudioprocess = function(e){	
                                        //Data buffer from mic ouput
					var buffer = e.inputBuffer.getChannelData(0);
	                           
                               var output     Lame.encode_buffer_ieee_float(mp3codec, buffer, buffer); 
		};

And the output is a UInt8Array which, when constructed into a blob, gives a nice neat mp3 file.

When I feed the same array into lamejs, it gives me silence:

        var output = mp3encoder.encodeBuffer(buffer);

I see in the examples that you feed an Int16Array into the encoder, and when I convert the Float32Array into a Int16Array I get the same output - just silence.  any idea what I'm doing wrong?

**Comment by zhuker** [comment]
how do you convert from float32array to int16array?

**Comment by zhuker** [comment]
do you use  output = mp3encoder.flush(); ?

**Comment by sb2702** [comment]
var   in16array =  new Int16Array(float32array.buffer); 

Actually: http://stackoverflow.com/questions/25839216/convert-float32array-to-int16array Using solution #1 was giving me garbage, it works using solution number #2, which I just tried

     var data = ...; /*new Float32Array();*/
     var len = data.length, i = 0;
     var dataAsInt16Array = new Int16Array(len);

    while(i < len)
         dataAsInt16Array[i] = convert(data[i++]);

     function convert(n) {
            var v = n < 0 ? n * 32768 : n * 32767;       // convert in range [-32768, 32767]
            return Math.max(-32768, Math.min(32768, v)); // clamp
       }
