### ISSUE TITLE
Rhythmic clicking in worker example

### ISSUE THREAD

**Issue by aaronkelly111** [zhuker/lamejs#20]
This is great work Alex, the speed is perfect. I've got a problem with the worker-example however, the resulting mp3 seems to have an intermittent rhythmic click presumably a side effect of the buffers getting joined together. It's not that noticeable but becomes more obvious when gain is applied afterwards.

Any ideas how to eliminate this, or somehow 'smooth/blend' the buffer edges into one another to achieve the same thing?

**Comment by zhuker** [comment]
Are you running the example unmodified?

**Comment by aaronkelly111** [comment]
Yeah, just running as is, nothing changed at all. It would probably be fine if I could use the resulting mp3 as is, but I need to normalize it up to a music standard 89dB. If you up the gain by running it though mp3gain (defaults to 89dB) or something similar then the clicking/cracking becomes much more obvious.

**Comment by kenbochr** [comment]
I also want to say that this is a great job! But I am also experiencing small, repetitive clicking noises when recording with the mic.html example. It works fine though with the index.html converter example.

**Comment by kenbochr** [comment]
I have recorded an oscillator and It looks like there are missing 5 ms every 650 ms. Here's an example on a cut out of the wave form. It should have been a smooth sine curve:
![screenshot_2](https://cloud.githubusercontent.com/assets/16125242/11612792/2e4004c0-9c08-11e5-8881-562739236472.png)

**Comment by zhuker** [comment]
Now that's a great piece of research!
Thanks

**Comment by kenbochr** [comment]
Ah - got it. In worker-realtime.js, the for statement didn't run through all samples.
So in the function encode:
Change: for (var i = 0; remaining >= maxSamples; i += maxSamples){
To: for (var i = 0; remaining >= 0; i += maxSamples) {

**Comment by aaronkelly111** [comment]
Awesome Ken! Just gave that a test and worked perfectly, great investigation and resolution!
You can generate a pull request if you want credit for the fix. If not it's a tiny edit for Alex.

Either way I'm happy to close this issue off.

**Comment by zhuker** [comment]
thanks @kenbochr @aaronkelly111
