### ISSUE TITLE
Licensing: LGPL version unclear

### ISSUE THREAD

**Issue by Jannis** [zhuker/lamejs#25]
Hi,

would you care to clarify which version of the LGPL `lamejs` is licensed under? E.g. 2.1 or 3.0? A good idea might be to mention it in `README.md` and put a link to the full license in the `LICENSE` file.

**Comment by Jannis** [comment]
Actually, `package.json` mentions LGPL 3.0, so nevermind. It could be made more clear though.

**Comment by zhuker** [comment]
The logic was to copy license from libmp3lame
