### ISSUE TITLE
Uncaught TypeError: Cannot read property 'readHeader' of undefined

### ISSUE THREAD

**Issue by khoner** [zhuker/lamejs#26]
Tried using the library but always got the same error in my script using Chrome: Uncaught TypeError: Cannot read property 'readHeader' of undefined.

Then copied example file to my server and tried reading a mono 8 and 16 bit wav file. Same error at line:

var wav = lamejs.WavHeader.readHeader(new DataView(audioData));

The file is being read in correctly. The audio data is there. Just not finding the error in the library.

**Comment by geeee** [comment]
The error message you provided means that `lamejs.WavHeader` is undefined. Please recheck if lamejs is imported correctly and if you are not redefining `lamejs` variable anywhere.

**Comment by khoner** [comment]
Thanks for getting back to me so quickly. I’m using the lame.all.js file. Do I still need to import? 

Best Regards,
Ken

**Comment by geeee** [comment]
Nope, lame.all.js should be enough. Is your server publicly accessible? Can I take a look at the page with the error? I'm interested in the value of lamejs variable right before that line.

**Comment by khoner** [comment]
So, I can’t really explain this, but I was playing around with worker-example and after uploading the three javascript files, I got that to work. Suddenly, the original example is working as well. 

http://www.kindredpix.com/lamejs/wav2mp3.html

My custom script is still giving an error, but now it’s a different error. Hopefully I can figure it out. That page is harder to give access to as it blocks all non-users. 

Thanks,
Ken

**Comment by geeee** [comment]
Maybe problem was with the caching or something like that. I'll close this issue if the example is working as expected now.
