### ISSUE TITLE
Add support for webpack

### ISSUE THREAD

**Issue by decademoon** [zhuker/lamejs#28]
Currently it's not possible to use this library with webpack. If I try to require it, I get errors like:

```
ERROR in ./~/lamejs/src/js/lametest.js
Module not found: Error: Cannot resolve module 'fs' in node_modules/lamejs/src/js
 @ ./~/lamejs/src/js/lametest.js 3:5-18
```

I don't really want to use `lame.all.js` or `lame.min.js` directly, webpack should be able to build the library.

**Comment by danielbanfield** [comment]
the reason for this is kind of... haha... lame (sorry, no offence to the author, great lib ;) I just couldn't resist it). it seems the library's primary file is lametest.js, which has both the Mp3Encoder definition as well as a bunch of tests that use 'fs', which web pack will try and compile with failure.

If you remove the tests and the fs = require('fs'); from the top, this works (at least webpack is fine, I have other issues with the encoding itself)..

I suggest a change to move the tests and the import of 'fs' to a separate file outside of src/js e.g. tests/js.

**Comment by zhuker** [comment]
Good point.
Pull requests are very welcome.
