### ISSUE TITLE
Small clicks between encoded chunks when concatenated

### ISSUE THREAD

**Issue by jaymo107** [zhuker/lamejs#53]
Hi, I'm using chunk based encoding method where I'm grabbing the WAV blob after 1 second intervals, encoding it and then appending the encoded mp3 data to an array where I build the final blob with the encoded mp3 data.

When the chunks of the WAV files are listened too they're clear but the mp3's seem to have a little click between each of the chunks after encoding. (You can listen to the mp3 here https://clyp.it/vbaf0zg1) 

This is my encoding code which is pretty much the same as a lot of peoples.

``` javascript
for (var i = 0; i < leftSamples.length; i += sampleBlockSize) {
            buffer = mp3encoder.encodeBuffer(
                leftSamples.subarray(i, i + sampleBlockSize),
                rightSamples.subarray(i, i + sampleBlockSize)
            );
            if (buffer.length > 0) {
                mp3Data.push(new Int8Array(buffer));
            }
        }

        buffer = mp3encoder.flush();

        // Push any leftover blocks into the mp3 data array
        if (buffer.length > 0) {
            mp3Data.push(new Int8Array(buffer));
        }
```

When I log the `mp3Data` once every chunk is encoded I get something that looks like this, if anyone wants to see what the data looks like.

<img width="1167" alt="screen shot 2018-02-13 at 12 10 21" src="https://user-images.githubusercontent.com/2669541/36149240-eb5ca994-10b6-11e8-91d4-58ca89e8a585.png">

I'm not sure if theres anything that could be stripped from the chunk to make them fit together more smoothly? Or any ideas why this could be happening?

I appreciate any help and thanks for such a great library!

James

**Comment by jaymo107** [comment]
If anyone has done this sort of splitting up of a recording and encoding each chunk, and has a better way of doing this, that would be a massive help also. Just running out of ideas with this.

**Comment by geeee** [comment]
Hi. The code you provided looks fine as it is, so the problem might be elsewhere.
Do you reinitialize `mp3encoder` before each chunk is encoded?

**Comment by jaymo107** [comment]
I do yeah, sorry I haven't shared that portion of the code, just above the for loop, where sample rate is `44100` and kbps is `128`.

``` js
var mp3encoder = new lamejs.Mp3Encoder(2, sampleRate, kbps);
```

So for every chunk this is all initialised again as each chunk is encoded in a web worker, so all this is executed per chunk, but should be using the same info anyway.

(p.s. thank you for your response 😄  )

**Comment by geeee** [comment]
LAME [adds silence](http://lame.sourceforge.net/tech-FAQ.txt) to the start and the end of encoded mp3s. This might be the cause of the "clicks".
Try to use single `Mp3Encoder` instance to encode all of your wav chunks, flushing it only once at the very end.

**Comment by jaymo107** [comment]
Ok thanks so much, I'll give this a go 👍

**Comment by jaymo107** [comment]
@geeee This worked, took us weeks to figure this out haha! Thank you very much for your help 🎉

**Comment by mperezguendulain** [comment]
Can some help me please??
I use a single Mp3Encoder instance to encode all my wav chunks, and I flushing only once, but I have the problem yet.

This is my code: 
https://gist.github.com/mperezguendulain/3ef390647b274916618cfe0521a9f6bd

I'd really appreciate it if you'd help me.
