### ISSUE TITLE
Can you add a license file to this repo?

### ISSUE THREAD

**Issue by shanewho** [zhuker/lamejs#6]
I'm guessing the license would be LGPL like LAME?

**Comment by Dewsworld** [comment]
+1

**Comment by zhuker** [comment]
i am no big license experts
you think it should be LGPL? why? @shanewho @Dewsworld

**Comment by Dewsworld** [comment]
I am using a different library for converting mp3. This lib is lighter and simpler, was hoping to use in our project if all our requirement satisfy... I'm no expert in license either. Just to clarify if it's okay to use in our project.

**Comment by shanewho** [comment]
I think it has to be LGPL because LAME is LGPL and so is jump3r-code. LGPL requires derivative work to be licensed under the same license. Here is the note in the license:

http://lame.sourceforge.net/license.txt
```
3. If you make modifications to LAME, you *must* release these
   modifications back to the LAME project, under the LGPL.
```

I would probably just copy the [LICENSE file from the java code](https://github.com/zhuker/lamejs/blob/master/src/main/java/LICENSE) in your src/main/java/LICENSE to the root of your repository: 

https://github.com/zhuker/lamejs/blob/master/src/main/java/LICENSE

**Comment by zhuker** [comment]
@shanewho done

**Comment by shanewho** [comment]
:+1:  Thanks!

**Comment by zhuker** [comment]
@Dewsworld - use at will, just mention you are using it, reference lamejs and lame somewhere and if you change it (like fix a bug) make your change available for everybody.
