### ISSUE TITLE
Convert Buffered mp3 stereo data to mp3 mono

### ISSUE THREAD

**Issue by legendvijay** [zhuker/lamejs#60]
Hi Guys,

       I have an requirement of Converting the Mp3 file from Stereo to Mono.
I get the MP3 Stereo data in to buffer using aurora.js and now i want create a mono mp3 out of that, How should i pick data for mono out of 2 channels.

**Comment by zhuker** [comment]
easy way:
you can pick either left or right channel and call that mono
harder way:
downmix left and right channels by averaging left and right channels `(left+right) / 2`
