### ISSUE TITLE
GainAnalysis

### ISSUE THREAD

**Issue by jamziir** [zhuker/lamejs#63]
hello
how to use GainAnalysis module ?

thanks

**Comment by zhuker** [comment]
its an internal class, public api is not exposed

**Comment by jamziir** [comment]
i have tow problem:
if decries samplerate my audio time increased and playing audio slowly (i calculate samplerate factor and decries buffer but problem not solve for all sample rate ) !
I need normalize my audio, for this propose i think need to GainAnalysis, how to normalize audio?

thanks a lot.
