### ISSUE TITLE
MP3 convertion with RecordRTC input

### ISSUE THREAD

**Issue by rehoehle** [zhuker/lamejs#8]
I have a problem regarding lamejs working together with RecordRTC. So i found RecrodRTC and i think its a great project to record audio and video in a browser. So i tried RecordRTC and the lib created a wav file (blob) and it was working well. But when i add that data as Int16Array to lamejs i get no data back the result has every time 835 byte. 

The input data and length look correct butt i get not result. 
![screenshot at aug 27 18-21-01](https://cloud.githubusercontent.com/assets/223007/9526241/65b35674-4ce8-11e5-96a2-6f6a46ec611a.png)

does anyone know a solution for that problem? Here my code. 

	// Stop recording and get data
	recordRTC.stopRecording(function() {
		var recordedBlob = recordRTC.blob;

		var reader = new FileReader();
		reader.onload = function(event) {
			var buffer = event.target.result;
			var mp3Blob = new Blob([encodeMP3(buffer)], {type: 'audio/mp3'});
			setUploadAudioData(mp3Blob);
		};
		reader.readAsArrayBuffer(recordedBlob);
	});

	var encodeMP3 = function(buffer) {
		var samples = new Int16Array(buffer);
		console.log(samples);
		console.log(samples.byteLength);
		mp3encoder = new liblame.Mp3Encoder(1, 44100, 128);
		mp3encoder.encodeBuffer(samples);
		var mp3Data = mp3encoder.flush();
		console.log(mp3Data);
                return mp3Data;
	};

**Comment by shanewho** [comment]
```
mp3encoder.encodeBuffer(samples);
    var mp3Data = mp3encoder.flush();
    console.log(mp3Data);
```

You get encoded data from the encodeBuffer call AND the flush call. You are only logging the result of the flush, which is just a tiny bit of the data. You need to capture the array returned from encodeBuffer as well.

**Comment by rehoehle** [comment]
What? That is exact the sample from the page? And that is working in my current version its only not working with the RecordRTC data and what do you suggest to get the correct data and the complete data?

**Comment by shanewho** [comment]
I could be wrong, but looking at this code I'm not sure how it would work at all:

Here you call encodeMP3(buffer) and use the result in the blob:
```
var mp3Blob = new Blob([encodeMP3(buffer)], {type: 'audio/mp3'});
```

But the encodeMP3 function doesn't actually return any value (i.e., there is no return statement in the function). So the value of the blob is created with an array whose only value is `undefined`.

The encodeMP3 function needs to use the result of encodeBuffer `var data = mp3encoder.encodeBuffer(samples)` as well as the result of .flush(). These will be 2 different arrays but you need the data from both of them to get your full mp3. 

Here is some code I use, you can hopefully see the difference:
https://github.com/zhuker/lamejs/issues/7#issuecomment-127298370

**Comment by rehoehle** [comment]
Yes i know ;) its for debugging... i know that there is no return... that is not the problem... the problem is that the output from the lame lib is empty... and to short. In my old version i use 

	mp3encoder = new lame.Mp3Encoder(1, 44100, 192);
	mp3data = mp3encoder.encodeBuffer(e.data.buf);

that code. And its working well. That make not so much sense because encode buffer and the flush result is stored in the same variable and overwrite the preview one. So how should that work? Then flush have to return the complete data and overwrite the previews data its not appending i think or what do you think?

**Comment by rehoehle** [comment]
Ok i have tested some more and your right now i get the data but i sound like Darth Vader :D any suggestions on that? The record has the double length and is slower.

**Comment by shanewho** [comment]
My only guess is that the buffer you are recording is stereo and you are encoding it as mono/single channel. If that's the case, you'd have to figure out how to split the buffer into 2 arrays, and pass them both to lame encodeBuffer (and make the Mp3Encoder constructor specify 2 channel). This may not be correct but that is my best guess.

**Comment by rehoehle** [comment]
Ok i found in the documentation, that the recording from RecordRTC is stereo only. So i have a blob where i have the stereo data. I try to find how to get the left and right channel separately.

**Comment by zhuker** [comment]
Stereo is interleaved that is you have one 16 bit sample of left followed
by a sample of right.
You essentially split the stereo into two putting every i-th item into left
array and every i+1-th item into right.
They call it deinterleave.

**Comment by rehoehle** [comment]
Thx for your reply. Then i try to implement that. Do you know some code where the interleave is implemented?

**Comment by rehoehle** [comment]
Yes i ment that :) thx then i can close that ticket :)

**Comment by shamseerahammedm** [comment]
@rehoehle  do u have any implemented sameple code of this recordrtc to mp3?

**Comment by rehoehle** [comment]
@shamseerahammedm this is an older post and i don't use this anymore so i can't give you some code. But in the end it was working.
